apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:1.14.2
